repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0 # Modify this to be the version you want
    hooks:
      - id: pydocstyle
        language: system
        types: [python]
        args:
        - --ignore=D401,D213

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - --fail-under=8

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        language: system
        pass_filenames: false
        types: [python] # Opcional: se você quiser que isso seja executado apenas quando arquivos Python forem alterados.
        args: ["--ignore-vuln","PYSEC-2021-878"]
