site_name: Data Project

repo_url: https://github.com/haroldoproenca/etlproject

theme:
  font:
    text: Work Sans
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: deep purple
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: orange
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/extract.md
    - getting-started/transform.md
    - getting-started/load.md
  - LinkedIn: linkedin.md
