[tool.poetry]
name = "dataproject"
version = "0.1.0"
description = "ETL Project"
authors = ["Haroldo Proenca"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
